import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "./Providers/LenisProvider";
import Navbar from "./Components/Navbar/Navbar";
import { Koulen, DM_Mono, Host_Grotesk } from "next/font/google";
import { Provider } from "../components/ui/provider";
import Footer from "./Components/Footer/Footer";

const koulen = Koulen({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-koulen",
});

const hostGrotesk = Host_Grotesk({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-host-grotesk",
});

const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-dm-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="grammarly-disable-editor" content="true" suppressHydrationWarning/>
      </head>
      <body
        suppressHydrationWarning
        className={`${koulen.variable} ${hostGrotesk.variable} ${dmMono.variable} antialiased`}
      >
        <Navbar />
        <LenisProvider>
           {children}
        </LenisProvider>
        <Footer />
      </body>
    </html>
  );
}
